fleet_project/cars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.contrib.auth.views import LogoutView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("", views.dashboard_view, name="dashboard"),
    # Car URLs
    path("car-add/", views.car_add_view, name="car_add"),
    path("car-delete/<int:car_id>/", views.car_delete_view, name="car_delete"),
    path("car-modify/<int:car_id>/", views.car_modify_view, name="car_modify"),
    path("car-details/<int:car_id>/", views.car_details_view, name="car_details"),
    path("car-list/", views.car_list_view, name="car_list"),
    # Client URLs
    path("client-add/", views.client_add_view, name="client_add"),
    path(
        "client-delete/<int:client_id>/", views.client_delete_view, name="client_delete"
    ),
    path(
        "client-modify/<int:client_id>/", views.client_modify_view, name="client_modify"
    ),
    path(
        "client-details/<int:client_id>/",
        views.client_details_view,
        name="client_details",
    ),
    path("client-list/", views.client_list_view, name="client_list"),
    # Order URLs
    path("order-add/<int:car_id>/", views.order_add_view, name="order_add"),
    path("order-delete/<int:order_id>/", views.order_delete_view, name="order_delete"),
    path("order-modify/<int:order_id>/", views.order_modify_view, name="order_modify"),
    path(
        "order-details/<int:order_id>/", views.order_details_view, name="order_details"
    ),
    path("order-list/", views.order_list_view, name="order_list"),
    # Driver URLs
    path("driver-add/", views.driver_add_view, name="driver_add"),
    path("driver-list/", views.driver_list_view, name="driver_list"),
    path(
        "driver-delete/<int:driver_id>/", views.driver_delete_view, name="driver_delete"
    ),
    path(
        "driver-modify/<int:driver_id>/", views.driver_modify_view, name="driver_modify"
    ),
    path(
        "driver-details/<int:driver_id>/",
        views.driver_details_view,
        name="driver_details",
    ),
    # Fleet Manager URLs
    path("fleetmanager-add/", views.fleet_manager_add_view, name="fleetmanager_add"),
    path("fleetmanager-list/", views.fleet_manager_list_view, name="fleetmanager_list"),
    path(
        "fleetmanager-delete/<int:fleetmanager_id>/",
        views.fleet_manager_delete_view,
        name="fleetmanager_delete",
    ),
    path(
        "fleetmanager-modify/<int:fleetmanager_id>/",
        views.fleet_manager_modify_view,
        name="fleetmanager_modify",
    ),
    path(
        "fleetmanager-details/<int:fleetmanager_id>/",
        views.fleet_manager_details_view,
        name="fleetmanager_details",
    ),
    # Service History URLs
    path(
        "servicehistory-add/", views.service_history_add_view, name="servicehistory_add"
    ),
    path(
        "servicehistory-list/",
        views.service_history_list_view,
        name="servicehistory_list",
    ),
    path(
        "servicehistory-delete/<int:servicehistory_id>/",
        views.service_history_delete_view,
        name="servicehistory_delete",
    ),
    path(
        "servicehistory-modify/<int:servicehistory_id>/",
        views.service_history_modify_view,
        name="servicehistory_modify",
    ),
    path(
        "servicehistory-details/<int:servicehistory_id>/",
        views.service_history_details_view,
        name="servicehistory_details",
    ),
    # Availability URLs
    path("availability-add/", views.availability_add_view, name="availability_add"),
    path("availability-list/", views.availability_list_view, name="availability_list"),
    path(
        "availability-delete/<int:availability_id>/",
        views.availability_delete_view,
        name="availability_delete",
    ),
    path(
        "availability-modify/<int:availability_id>/",
        views.availability_modify_view,
        name="availability_modify",
    ),
    path(
        "availability-details/<int:availability_id>/",
        views.availability_details_view,
        name="availability_details",
    ),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

fleet_project/fleet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cars/', include('cars.urls')),
    path('', include('cars.urls'))
]

fleet_project/cars/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from datetime import datetime, timedelta
from django.contrib.auth.models import User

# Create your models here.


class FleetUser(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.TextField()
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=20, unique=True)
    driver_license = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Client(FleetUser):
    max_rental_days = models.PositiveIntegerField(default=3)
    is_vip = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Driver(FleetUser):
    hire_date = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class FleetManager(FleetUser):

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Car(models.Model):
    BODY_TYPES = [
        ("Hatchback", "Hatchback"),
        ("Sedan", "Sedan"),
        ("Liftback", "Liftback"),
        ("Kombi", "Kombi"),
        ("SUV", "SUV"),
        ("Van", "Van"),
        ("Cupe", "Cupe"),
        ("Roadster", "Roadster"),
        ("Cabriolet", "Cabriolet"),
        ("Pick-up", "Pick-up"),
    ]

    FUEL_TYPES = [
        ("Petrol", "Petrol"),
        ("Diesel", "Diesel"),
        ("Hybrid PHEV", "HHybrid PHEV"),
        ("Hybrid HEV", "Hybrid HEV"),
        ("Electric", "Electric"),
        ("Hydrogen", "Hydrogen"),
    ]

    TECHNICAL_CONDITION = [
        ("Good condition", "Good condition"),
        ("Need basic service", "Need basic service"),
        ("Need advanced service", "Need advanced service"),
    ]

    brand = models.CharField(max_length=100)  # nazwa marki
    model = models.CharField(max_length=100)  # nazwa model
    year = models.IntegerField()  # rok produkcji
    model_year = models.IntegerField()  # modelowy rok produkcji
    vin_number = models.CharField(max_length=17)  # numery VIN posiadają 17 znaków
    mileage = models.PositiveIntegerField()  # przebieg - musi być dodatny
    registration_number = models.CharField(
        max_length=10
    )  # w polsce standard to 7 znaków, indywidualne więcej
    body_type = models.CharField(
        max_length=20, choices=BODY_TYPES
    )  # rodzaj nadwozia z słownika
    fuel_type = models.CharField(
        max_length=20, choices=FUEL_TYPES
    )  # rodzaj napędu z słownika
    engine_capacity = models.DecimalField(
        max_digits=5, decimal_places=2, null=True
    )  # pojemność silnika
    engine_power = models.PositiveIntegerField()  # moc układu napędowego
    fuel_consumption_1 = models.DecimalField(
        max_digits=6, decimal_places=2
    )  # spalanie cykl niski
    fuel_consumption_2 = models.DecimalField(
        max_digits=6, decimal_places=2
    )  # spalanie cykl średni
    fuel_consumption_3 = models.DecimalField(
        max_digits=6, decimal_places=2
    )  # spalanie cykl wysoki
    color = models.CharField(max_length=50)  # kolor nadwozia
    technical_condition = models.CharField(
        max_length=30, choices=TECHNICAL_CONDITION
    )  # stan techniczny czy sprawny lub uszkodzony
    equipment_list = models.TextField(blank=True, null=True)  # dodatkowe wyposażenie
    seats = models.PositiveIntegerField()  # liczba siedzeń
    trunk_space = models.PositiveIntegerField()  # pojemność bagażnika
    catalog_price = models.DecimalField(
        max_digits=10, decimal_places=2
    )  # cena katalogowa w momencie produkcji
    last_service_date = models.DateField(null=True)  # data ostatniego przeglądu
    service_interval_km = models.PositiveIntegerField(
        default=30000
    )  # interwał przeglądu w kilometrach
    service_interval_months = models.PositiveIntegerField(
        default=12
    )  # interwał przeglądu w miesiącach
    damage = models.TextField(blank=True, null=True)  # uszkodzenia samochodu

    def needs_service(self):
        if self.last_service_date is None:
            return True  # Samochód jeszcze nie miał przeglądu
        # Konwertujemy self.last_service_date na obiekt datetime.datetime
        last_service_datetime = timezone.make_aware(
            datetime.combine(self.last_service_date, datetime.min.time())
        )
        # Obliczamy różnicę czasu
        days_since_service = (timezone.now() - last_service_datetime).days
        if days_since_service >= self.service_interval_months * 30:
            return True
        if self.mileage >= self.service_interval_km:
            return True
        return False

    def create_year_availability(self):
        current_year = timezone.now().year
        for month in range(1, 13):
            start_date = timezone.datetime(current_year, month, 1)
            end_date = start_date + timedelta(
                days=30
            )  # przy założeniu że miesiąc ma 30 dni
            availability = Availability(
                car=self, start_date=start_date, end_date=end_date, status="Available"
            )
            availability.save()

    def save(self, *args, **kwargs):
        if self.pk is None:  # Jeśli samochód jest nowo utworzony
            super().save(*args, **kwargs)  # zapisanie by uzyskać ID samochodu
            self.create_year_availability()  # utworzenie dostępności na rok od momentu dodania samochodu
            self.last_service_date = (
                timezone.now()
            )  # Ustaw datę ostatniego przeglądu na bieżącą datę
            super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.brand} {self.model}"


class ServiceHistory(models.Model):
    car = models.ForeignKey("Car", on_delete=models.CASCADE)
    service_date = models.DateField()  # data serwisu
    description = models.TextField()  # opis napraw/czynności
    cost = models.DecimalField(
        max_digits=10, decimal_places=2
    )  # koszt napraw/czynności

    def __str__(self):
        return f"Service for {self.car} on {self.service_date}"

    def save(self, *args, **kwargs):
        if (
            self.pk is None
        ):  # jeśli primarykey nie znajdzie w bazie danych, tworzy nowy samochód i robi przegląd
            car = self.car
            car.last_service_date = (
                self.service_date
            )  # Ustaw datę ostatniego przeglądu na datę serwisu
            car.save()  # Zapisz zmiany w modelu Car
        super().save(
            *args, **kwargs
        )  # jeśli primarykey istnieje, nadal zadziała funkcja save


class Availability(models.Model):
    car = models.ForeignKey("Car", on_delete=models.CASCADE)
    start_date = models.DateField()  # dostępność początkowa data
    end_date = models.DateField()  # dostępność końcowa data
    status_choices = {
        ("Available", "Available"),
        ("Reserved", "Reserved"),
        ("Service", "Service"),
        ("Buffer", "Buffer"),
    }
    status = models.CharField(
        max_length=20, choices=status_choices, default="Available"
    )

    def __str__(self):
        return f"Availability of {self.car} from {self.start_date} to {self.end_date}"


class Order(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)  # samochód
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE
    )  # klient otrzymujący samochód
    driver = models.ForeignKey(
        Driver, on_delete=models.CASCADE, related_name="orders_as_driver"
    )  # kierowca wykonujący
    pickup_date = models.DateField()  # data rozpoczęcia zlecenia
    return_date = models.DateField()  # data zakończenia zlecenia
    distance = models.PositiveIntegerField()  # odległość w kilometrach
    cost = models.PositiveIntegerField()  # koszt zlecenia
    settled = models.BooleanField(
        default=False
    )  # informacja czy zlecenie zostało rozliczone

    def save(self, *args, **kwargs):
        if self.pk is None:  # Jeśli to nowe zamówienie
            super().save(*args, **kwargs)
            # Aktualizacja dostępności samochodu na "Zarezerwowany"
            if self.car.availability_set.filter(status="Available").exists():
                availability = self.car.availability_set.filter(
                    status="Available"
                ).first()
                availability.status = "Reserved"
                availability.save()
        else:  # Jeśli to aktualizacja istniejącego zamówienia
            super().save(*args, **kwargs)


class Events(models.Model):
    name = models.CharField(max_length=255, null=True)
    start = models.DateTimeField(null=True)
    end = models.DateTimeField(null=True)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Calendar Events")
        verbose_name_plural = _("Calendar Events")


class Reservation(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    pickup_address = models.TextField()
    created_by_client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    created_by_fleet_manager = models.ForeignKey(
        FleetManager, on_delete=models.CASCADE, null=True
    )
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(null=True)
    canceled = models.BooleanField(default=False)
    canceled_by_client = models.BooleanField(default=False)
    canceled_by_fleet_manager = models.BooleanField(default=False)

    def __str__(self):
        return f"Reservation for {self.car} from {self.start_date} to {self.end_date}"

    def save(self, *args, **kwargs):
        if self.pk is None:

fleet_project/cars/templates/availability_modify.html
{% extends "__base__.html" %}
{% block title %}Modyfikuj Dostępność{% endblock title %}
{% block content %}
    <h1>Modyfikuj Dostępność</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="start_date">Data rozpoczęcia:</label>
            <input type="date" id="start_date" name="start_date" class="form-control" value="{{ availability.start_date }}">
        </div>
        <div class="form-group">
            <label for="end_date">Data zakończenia:</label>
            <input type="date" id="end_date" name="end_date" class="form-control" value="{{ availability.end_date }}">
        </div>
        <!-- Add a hidden input field for the availability ID -->
        <input type="hidden" name="availability_id" value="{{ availability.id }}">
        <button type="submit">Zapisz zmiany</button>
    </form>

    <!-- FullCalendar -->
    <div id="calendar"></div>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.10.1/main.min.css' rel='stylesheet' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.10.1/main.min.js'></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            // Prepare event data for FullCalendar
            var events = [{
                title: 'Dostępność',
                start: '{{ availability.start_date }}',
                end: '{{ availability.end_date }}',
                backgroundColor: 'green'
            }];

            // Initialize FullCalendar
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                events: events
            });
            calendar.render();
        });
    </script>
{% endblock content %}

fleet_project/cars/templates/car_add.html
{% extends "__base__.html" %}
{% block title %}Dodaj Samochód{% endblock title %}
{% block content %}
    <h1>Dodaj Samochód</h1>
    <form method="post" id="car-form">
        {% csrf_token %}
        <label for="brand">Marka:</label>
        <input type="text" id="brand" name="brand"><br>

        <label for="model">Model:</label>
        <input type="text" id="model" name="model"><br>

        <label for="year">Rok produkcji:</label>
        <input type="number" id="year" name="year" value="2020"><br>

        <label for="model_year">Modelowy rok produkcji:</label>
        <input type="number" id="model_year" name="model_year" value="2020"><br>

        <label for="vin_number">Numer VIN:</label>
        <input type="text" id="vin_number" name="vin_number"><br>

        <label for="mileage">Przebieg:</label>
        <input type="number" id="mileage" name="mileage"><br>

        <label for="registration_number">Numer rejestracyjny:</label>
        <input type="text" id="registration_number" name="registration_number"><br>

        <label for="body_type">Rodzaj nadwozia:</label>
        <select id="body_type" name="body_type">
            {% for body_type, _ in BODY_TYPES %}
                <option value="{{ body_type }}">{{ body_type }}</option>
            {% endfor %}
        </select><br>


        <label for="fuel_type">Rodzaj napędu:</label>
        <select id="fuel_type" name="fuel_type">
            {% for fuel_type, _ in FUEL_TYPES %}
                <option value="{{ fuel_type }}">{{ fuel_type }}</option>
            {% endfor %}
        </select><br>

        <label for="engine_capacity">Pojemność silnika:</label>
        <input type="number" id="engine_capacity" name="engine_capacity"><br>

        <label for="engine_power">Moc układu napędowego:</label>
        <input type="number" id="engine_power" name="engine_power"><br>

        <label for="fuel_consumption_1">Spalanie cykl niski:</label>
        <input type="number" id="fuel_consumption_1" name="fuel_consumption_1"><br>

        <label for="fuel_consumption_2">Spalanie cykl średni:</label>
        <input type="number" id="fuel_consumption_2" name="fuel_consumption_2"><br>

        <label for="fuel_consumption_3">Spalanie cykl wysoki:</label>
        <input type="number" id="fuel_consumption_3" name="fuel_consumption_3"><br>

        <label for="color">Kolor nadwozia:</label>
        <input type="text" id="color" name="color"><br>

        <label for="technical_condition">Stan techniczny:</label>
        <select id="technical_condition" name="technical_condition">
            {% for technical_condition, _ in TECHNICAL_CONDITION %}
                <option value="{{ technical_condition }}">{{ technical_condition }}</option>
            {% endfor %}
        </select><br>

        <label for="equipment_list">Dodatkowe wyposażenie:</label>
        <input type="text" id="equipment_list" name="equipment_list"><br>

        <label for="seats">Liczba siedzeń:</label>
        <input type="number" id="seats" name="seats" value="5"><br>

        <label for="trunk_space">Pojemność bagażnika:</label>
        <input type="number" id="trunk_space" name="trunk_space"><br>

        <label for="catalog_price">Cena katalogowa:</label>
        <input type="number" id="catalog_price" name="catalog_price"><br>

        <label for="last_service_date">Data ostatniego przeglądu:</label>
        <input type="date" id="last_service_date" name="last_service_date"><br>

        <label for="service_interval_km">Interwał przeglądu w kilometrach:</label>
        <input type="number" id="service_interval_km" name="service_interval_km" value="30000" step="1000"><br>

        <label for="service_interval_months">Interwał przeglądu w miesiącach:</label>
        <input type="number" id="service_interval_months" name="service_interval_months" value="12" step="1"><br>

        <label for="damage">Uszkodzenia:</label>
        <input type="text" id="damage" name="damage"><br>

        <button type="submit" class="btn btn-primary">Zapisz</button>
    </form>
{% endblock content %}

fleet_project/cars/templates/dashboard.html
{% extends "__base__.html" %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<div class="dashboard-header m-4">
    <div class="dashboard-alerts">
        <div class="alert-item alert-info">
            <i class="fas icon-circle fa-info-circle"></i>
            <span class="font-weight-bold">Liczba pojazdów: {{ car_count }}</span>
        </div>
        <div class="alert-item alert-light">
            <i class="far icon-calendar fa-calendar-alt"></i>
            <span class="font-weight-bold">Ostatnio dodany pojazd: {{ latest_added_car.brand }} {{ latest_added_car.model }}</span>
        </div>
        <div class="alert-item alert-warning">
            <i class="fas icon-circle fa-exclamation-circle"></i>
            <span class="font-weight-bold">Samochód z największym przebiegiem: {{ car_with_max_mileage.brand }} {{ car_with_max_mileage.model }} {{ car_with_max_mileage.mileage }} km</span>
        </div>
    </div>
</div>
{% endblock content %}

fleet_project/cars/templates/driver_list.html
{% extends "__base__.html" %}
{% block title %}Lista Kierowców{% endblock title %}
{% block content %}
    <h1>Lista Kierowców</h1>
    <ul>
        {% for driver in drivers %}
            <li>{{ driver.first_name }} {{ driver.last_name }} {{ driver.phone_number }}</li>
            <form action="{% url 'driver_delete' driver.pk %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Usuń</button>
            </form>
        {% endfor %}
    </ul>
{% endblock content %}

fleet_project/cars/templates/driver_modify.html
{% extends "__base__.html" %}
{% block title %}Modyfikuj Kierowcę{% endblock title %}
{% block content %}
    <h1>Modyfikuj Kierowcę</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">Imię:</label>
            <input type="text" id="first_name" name="first_name" class="form-control" value="{{ driver.first_name }}">
        </div>
        <div class="form-group">
            <label for="last_name">Nazwisko:</label>
            <input type="text" id="last_name" name="last_name" class="form-control" value="{{ driver.last_name }}">
        </div>
        <div class="form-group">
            <label for="address">Adres:</label>
            <input type="text" id="address" name="address" class="form-control" value="{{ driver.address }}">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" class="form-control" value="{{ driver.email }}">
        </div>
        <div class="form-group">
            <label for="phone_number">Numer telefonu:</label>
            <input type="tel" id="phone_number" name="phone_number" class="form-control" value="{{ driver.phone_number }}">
        </div>
        <div class="form-group">
            <label for="driver_license">Numer prawa jazdy:</label>
            <input type="text" id="driver_license" name="driver_license" class="form-control" value="{{ driver.driver_license }}">
        </div>
        <div class="form-group">
            <label for="hire_date">Data zatrudnienia:</label>
            <input type="date" id="hire_date" name="hire_date" class="form-control" value="{{ driver.hire_date }}">
        </div>
        <button type="submit">Zapisz zmiany</button>
    </form>
{% endblock content %}

fleet_project/cars/templates/fleetmanager_add.html
{% extends "__base__.html" %}
{% block title %}Dodaj Managera Floty{% endblock title %}
{% block content %}
    <h1>Dodaj Managera Floty</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">Imię:</label>
            <input type="text" id="first_name" name="first_name" class="form-control">
        </div>
        <div class="form-group">
            <label for="last_name">Nazwisko:</label>
            <input type="text" id="last_name" name="last_name" class="form-control">
        </div>
        <div class="form-group">
            <label for="address">Adres:</label>
            <input type="text" id="address" name="address" class="form-control">
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" class="form-control">
        </div>
        <div class="form-group">
            <label for="phone_number">Numer telefonu:</label>
            <input type="text" id="phone_number" name="phone_number" class="form-control">
        </div>
        <button type="submit">Dodaj</button>
    </form>
{% endblock content %}

fleet_project/cars/templates/fleetmanager_details.html
{% extends "__base__.html" %}
{% block title %}Szczegóły Menedżera Floty{% endblock title %}
{% block content %}
    <h1>Szczegóły Menedżera Floty</h1>
    <p>Imię: {{ fleet_manager.first_name }}</p>
    <p>Nazwisko: {{ fleet_manager.last_name }}</p>
    <p>Numer Telefonu: {{ fleet_manager.phone_number }}</p>
{% endblock content %}

fleet_project/cars/templates/fleetmanager_list.html
{% extends "__base__.html" %}
{% block title %}Lista Menedżerów Floty{% endblock title %}
{% block content %}
    <h1>Lista Menedżerów Floty</h1>
    <ul>
        {% for fleet_manager in fleet_managers %}
            <li>{{ fleet_manager }}</li>
            <form action="{% url 'fleetmanager_delete' fleet_manager.pk %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Usuń</button>
            </form>
        {% endfor %}
    </ul>
{% endblock content %}

fleet_project/cars/templates/index.html
{% extends "__base__.html" %}
{% block title %}Strona główna{% endblock title %}
{% block content %}
<div class="container">
    <h1 class="my-4">Witaj na stronie głównej!</h1>
    <p>Jest to aplikacja do zarządzania flotą samochodów którą można łatwo przystosować do innych produktów</p>
    <p>oraz innej formy zarządzania flotą samochodów!</p>
</div>
{% endblock content %}

fleet_project/cars/templates/order_list.html
{% extends "__base__.html" %}
{% block title %}Lista Zamówień{% endblock title %}
{% block content %}
    <h1>Lista Zamówień</h1>
    <ul>
    {% for order in orders %}
        <li>{{ order.description }}</li>
            <form action="{% url 'order_delete' order.pk %}" method="post" style="display: inline;">
                {% csrf_token %}
            <button type="submit" class="btn btn-danger">Usuń</button>
            </form>
    {% empty %}
        <li>Brak zamówień</li>
    {% endfor %}
    </ul>
{% endblock content %}

fleet_project/cars/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" id="id_username">

        <label for="id_password1">Password:</label>
        <input type="password" name="password1" id="id_password1">

        <label for="id_password2">Password confirmation:</label>
        <input type="password" name="password2" id="id_password2">

        <label for="id_first_name">First name:</label>
        <input type="text" name="first_name" id="id_first_name">

        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" id="id_last_name">

        <label for="id_address">Address:</label>
        <input type="text" name="address" id="id_address">

        <label for="id_email">Email:</label>
        <input type="email" name="email" id="id_email">

        <label for="id_phone_number">Phone number:</label>
        <input type="text" name="phone_number" id="id_phone_number">

        <label for="id_driver_license">Driver license:</label>
        <input type="text" name="driver_license" id="id_driver_license">

        <button type="submit">Register</button>
    </form>
</body>
</html>

fleet_project/cars/templates/servicehistory_add.html
{% extends "__base__.html" %}
{% block title %}Dodaj Historię Serwisu{% endblock title %}
{% block content %}
    <h1>Dodaj Historię Serwisu</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="car_id">ID Samochodu:</label>
            <input type="text" id="car_id" name="car_id" class="form-control">
        </div>
        <div class="form-group">
            <label for="service_date">Data Serwisu:</label>
            <input type="date" id="service_date" name="service_date" class="form-control">
        </div>
        <div class="form-group">
            <label for="description">Opis:</label>
            <textarea id="description" name="description" class="form-control" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="cost">Koszt:</label>
            <input type="number" id="cost" name="cost" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
{% endblock content %}

fleet_project/cars/templates/servicehistory_details.html
{% extends "__base__.html" %}
{% block title %}Szczegóły Historii Serwisu{% endblock title %}
{% block content %}
    <h1>Szczegóły Historii Serwisu</h1>
    <p>Data Serwisu: {{ service_history.service_date }}</p>
    <p>Opis: {{ service_history.description }}</p>
    <p>Koszt: {{ service_history.cost }}</p>

{% endblock content %}